# Generated by Django 3.2.4 on 2021-06-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('VIN', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('Patente', models.CharField(max_length=6)),
                ('Año_Fabricacion', models.IntegerField()),
                ('Fecha_de_Recepcion', models.DateTimeField()),
                ('Marca', models.CharField(max_length=200)),
                ('Modelo', models.CharField(max_length=200)),
            ],
        ),
    ]
