# Generated by Django 3.2.4 on 2021-06-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='Año_Fabricacion',
            field=models.PositiveIntegerField(),
        ),
    ]
